### ISSUE TITLE
Can I send an email with an attachment

### ISSUE THREAD

**Issue by tianxia0079** [mrz1836/go-mail#1]
Can I send an email with an attachment

**Comment by mrz1836** [comment]
Yes - checkout out /examples/example.go:

https://github.com/mrz1836/go-mail/blob/da89ba933b97e3a86a43bdd33cab5de7510a678e/examples/examples.go#L273

**Comment by mrz1836** [comment]
Let me know if you have any other issues/suggestions ;-)
